set nocompatible
filetype off
filetype plugin indent on
" General settings

let mapleader=","
set backspace=indent,eol,start
set ruler
set number
set showcmd
set incsearch
set hlsearch
set ignorecase
set smartcase

" Indentation
set expandtab
set shiftwidth=2
set tabstop=2

" look and feel
set background=dark
set colorcolumn=100

" always show statusline
set laststatus=2

syntax on

set nobackup
set nowritebackup
set noswapfile
set noundofile

" forget about arrows
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

" easy tab navigation
map <C-e> <ESC>:tabnew 

" split pane navigation
nmap <silent> <C-k> :wincmd k<CR>
nmap <silent> <C-j> :wincmd j<CR>
nmap <silent> <C-h> :wincmd h<CR>
nmap <silent> <C-l> :wincmd l<CR>

" show insane characters
set lcs=tab:>-,trail:-
set list


imap <Leader>over`  ̀
imap <Leader>over'  ́
imap <Leader>over^  ̂
imap <Leader>overv  ̌
imap <Leader>over~  ̃
imap <Leader>over-  ̄
imap <Leader>over_  ̅
imap <Leader>over–  ̅
imap <Leader>over—  ̅
imap <Leader>overcup  ̆
imap <Leader>overcap  ̑
imap <Leader>over.  ̇
imap <Leader>over..  ̈
imap <Leader>over"  ̈
imap <Leader>over...  ⃛
imap <Leader>overright.  ͘
imap <Leader>overo  ̊
imap <Leader>over``  ̏
imap <Leader>over''  ̋
imap <Leader>overvec  ⃑
imap <Leader>vec  ⃑
imap <Leader>overlvec  ⃐
imap <Leader>lvec  ⃐
imap <Leader>overarc  ⃕
imap <Leader>overlarc  ⃔
imap <Leader>overto  ⃗
imap <Leader>overfrom  ⃖
imap <Leader>overfromto  ⃡
imap <Leader>over*  ⃰
imap <Leader>under`  ̖
imap <Leader>under'  ̗
imap <Leader>under,  ̗
imap <Leader>under.  ̣
imap <Leader>under..  ̤
imap <Leader>under"  ̤
imap <Leader>undero  ̥
imap <Leader>under-  ̱
imap <Leader>under_  ̲
imap <Leader>under–  ̲
imap <Leader>under—  ̲
imap <Leader>through~  ̴
imap <Leader>through-  ̵
imap <Leader>through_  ̶
imap <Leader>through–  ̶
imap <Leader>through—  ̶
imap <Leader>through/  ̷
imap <Leader>not  ̷
imap <Leader>through?  ̸
imap <Leader>Not  ̸
imap <Leader>through\|  ⃒
imap <Leader>throughshortmid  ⃓
imap <Leader>througho  ⃘

imap <Leader>{{ ⦃
imap <Leader>}} ⦄
imap <Leader>: ∶
imap <Leader>:: ∷
imap <Leader>;  ﹔
imap <Leader>.. ‥
imap <Leader>=? ≟
imap <Leader>all ∀
imap <Leader>always □
imap <Leader>approx ≈
imap <Leader>bot ⊥
imap <Leader>box □
imap <Leader>boxdot ⊡
imap <Leader>box. ⊡
imap <Leader>boxminus ⊟
imap <Leader>box- ⊟
imap <Leader>boxplus ⊞
imap <Leader>box+ ⊞
imap <Leader>boxtimes ⊠
imap <Leader>box* ⊠
imap <Leader>bul •
imap <Leader>C ℂ
imap <Leader>cdot ∙
imap <Leader>. ∙
imap <Leader>cdots ⋯
imap <Leader>check ✓
imap <Leader>yes ✓
imap <Leader>Check ✔
imap <Leader>Yes ✔
imap <Leader>circ ∘
imap <Leader>clock ↻
imap <Leader>cclock ↺
imap <Leader>comp ∘
imap <Leader>contra ↯
imap <Leader>deg °
imap <Leader>den ⟦⟧<left>
imap <Leader>diamond ◇
imap <Leader>dots …
imap <Leader>down ↓
imap <Leader>downtri ▼
imap <Leader>Down ⇓
imap <Leader>dunion ⊎
imap <Leader>du ⊎
imap <Leader>ell ℓ
imap <Leader>empty ∅
imap <Leader>equiv ≡
imap <Leader>eq ≡
imap <Leader>eventually ◇
imap <Leader>exists ∃
imap <Leader>flat ♭
imap <Leader>fold ⦇⦈<left>
imap <Leader>(\| ⦇
imap <Leader>\|) ⦈
imap <Leader>forall ∀
imap <Leader>from ←
imap <Leader><- ←
imap <Leader>From ⇐
imap <Leader>fromto ↔
imap <Leader>Fromto ⇔
imap <Leader>ge ≥
imap <Leader>glub ⊓
imap <Leader>iff ⇔
imap <Leader>implies ⇒
imap <Leader>impliedby ⇐
imap <Leader>in ∈
imap <Leader>infty ∞
imap <Leader>inf ∞
imap <Leader>int ∫
imap <Leader>intersect ∩
imap <Leader>iso ≅
imap <Leader>join ⋈
imap <Leader>land ∧
imap <Leader>langle ⟨
imap <Leader>lbrac ⟦
imap <Leader>[[ ⟦
imap <Leader>ldots …
imap <Leader>ldown ⇃
imap <Leader>leadsto ⇝
imap <Leader>~> ⇝
imap <Leader>le ≤
imap <Leader>lift ⌊⌋<left>
imap <Leader>floor ⌊⌋<left>
imap <Leader>llangle ⟪
imap <Leader>longto ⟶ 
imap <Leader>-- ⟶ 
imap <Leader>– ⟶ 
imap <Leader>lor ∨
imap <Leader>lower ⌈⌉<left>
imap <Leader>ceil ⌈⌉<left>
imap <Leader>lub ⊔
imap <Leader>lup ↿
imap <Leader>mapsto ↦
imap <Leader>map ↦
imap <Leader>mid ∣
imap <Leader>models ⊨
imap <Leader>\|= ⊨
imap <Leader>N ℕ
imap <Leader>ne ≠
imap <Leader>nearrow ↗
imap <Leader>Nearrow ⇗
imap <Leader>neg ¬
imap <Leader>/= ≠
imap <Leader>nequiv ≢
imap <Leader>neq ≢
imap <Leader>nexist ∄
imap <Leader>none ∄
imap <Leader>ni ∋
imap <Leader>ni ∋
imap <Leader>nin ∉
imap <Leader>niso ≇
imap <Leader>notin ∉
imap <Leader>nwarrow ↖
imap <Leader>Nwarrow ⇖
imap <Leader>oast ⊛
imap <Leader>odot ⊙
imap <Leader>o. ⊙
imap <Leader>of ∘
imap <Leader>o ∘
imap <Leader>ominus ⊖
imap <Leader>o- ⊖
imap <Leader>oplus ⊕
imap <Leader>o+ ⊕
imap <Leader>oslash ⊘
imap <Leader>o/ ⊘
imap <Leader>otimes ⊗
imap <Leader>o* ⊗
imap <Leader>par ∂
imap <Leader>pge ≽
imap <Leader>pgt ≻
imap <Leader>ple ≼
imap <Leader>plt ≺
imap <Leader>p≥ ≽
imap <Leader>p> ≻
imap <Leader>p≤ ≼
imap <Leader>p< ≺
imap <Leader>pm ±
imap <Leader>prec ≼
imap <Leader>prod ∏
imap <Leader>proves ⊢
imap <Leader>\|- ⊢
imap <Leader>provedby ⊣
imap <Leader>Q ℚ
imap <Leader>qed ∎
imap <Leader>R ℝ
imap <Leader>rangle ⟩
imap <Leader>rbrac ⟧
imap <Leader>]] ⟧
imap <Leader>rdown ⇂
imap <Leader>righttri ▸
imap <Leader>rrangle ⟫
imap <Leader>rup ↾
imap <Leader>searrow ↘
imap <Leader>Searrow ⇘
imap <Leader>setminus ∖
imap <Leader>sharp ♯
imap <Leader># ♯
imap <Leader>sim ∼
imap <Leader>simeq ≃
imap <Leader>some ∃
imap <Leader>sqge ⊒
imap <Leader>sqgt ⊐
imap <Leader>sqle ⊑
imap <Leader>sqlt ⊏
imap <Leader>s≥ ⊒
imap <Leader>s> ⊐
imap <Leader>s≤ ⊑
imap <Leader>s< ⊏
imap <Leader>sqr ²
imap <Leader>sqrt √
imap <Leader>star ✭
imap <Leader>subset ⊂
imap <Leader>sub ⊂
imap <Leader>subseteq ⊆
imap <Leader>subeq ⊆
imap <Leader>subsetneq ⊊
imap <Leader>subneq ⊊
imap <Leader>sum ∑
imap <Leader>supset ⊃
imap <Leader>sup ⊃
imap <Leader>supseteq ⊇
imap <Leader>supeq ⊇
imap <Leader>supsetneq ⊋
imap <Leader>supneq ⊋
imap <Leader>swarrow ↙
imap <Leader>Swarrow ⇙
imap <Leader>thus ∴
imap <Leader>times ×
imap <Leader>* ×
imap <Leader>to →
imap <Leader>- →
imap <C-_> →
imap <Leader>To ⇒
imap <Leader>= ⇒
imap <Leader>top ⊤
imap <Leader>tuple ⟨⟩<left>
imap <Leader>up ↑
imap <Leader>updown ↕
imap <Leader>ud ↕
imap <Leader>unfold ⦉⦊<left>
imap <Leader><\| ⦉
imap <Leader>\|> ⦊
imap <Leader>up;down ⇅
imap <Leader>u;d ⇅
imap <Leader>uptri ▲
imap <Leader>Up ⇑
imap <Leader>union ∪
imap <Leader>vdots ⋮
imap <Leader>voltage ⚡
imap <Leader>xmark ✗
imap <Leader>no ✗
imap <Leader>Xmark ✘
imap <Leader>No ✘
imap <Leader>Z ℤ

imap <Leader>sec §

imap <Leader>^0 ⁰
imap <Leader>^1 ¹
imap <Leader>^2 ²
imap <Leader>^3 ³
imap <Leader>^4 ⁴
imap <Leader>^5 ⁵
imap <Leader>^6 ⁶
imap <Leader>^7 ⁷
imap <Leader>^8 ⁸
imap <Leader>^9 ⁹
imap <Leader>^n ⁿ
imap <Leader>^i ⁱ
imap <Leader>^+ ⁺
imap <Leader>^- ⁻
imap <Leader>' ′
imap <Leader>'' ″
imap <Leader>''' ‴
imap <Leader>'''' ⁗
imap <Leader>" ″
imap <Leader>"" ⁗
imap <Leader>` ‵
imap <Leader>`` ‶
imap <Leader>``` ‷

imap <Leader>0 ₀
imap <Leader>1 ₁
imap <Leader>2 ₂
imap <Leader>3 ₃
imap <Leader>4 ₄
imap <Leader>5 ₅
imap <Leader>6 ₆
imap <Leader>7 ₇
imap <Leader>8 ₈
imap <Leader>9 ₉
imap <Leader>_i ᵢ
imap <Leader>_j ⱼ
imap <Leader>_+ ₊
imap <Leader>_- ₋
imap <Leader>p0 π₀
imap <Leader>p1 π₁
imap <Leader>p2 π₂
imap <Leader>p3 π₃
imap <Leader>p4 π₄
imap <Leader>p5 π₅
imap <Leader>p6 π₆
imap <Leader>p7 π₇
imap <Leader>p8 π₈
imap <Leader>p9 π₉
imap <Leader>i0 ι₀
imap <Leader>i1 ι₁
imap <Leader>i2 ι₂
imap <Leader>i3 ι₃
imap <Leader>i4 ι₄
imap <Leader>i5 ι₅
imap <Leader>i6 ι₆
imap <Leader>i7 ι₇
imap <Leader>i8 ι₈
imap <Leader>i9 ι₉

imap <Leader>alpha α
imap <Leader>a α
imap <Leader>beta β
imap <Leader>b β
imap <Leader>gamma γ
imap <Leader>g γ
imap <Leader>delta δ
imap <Leader>d δ
imap <Leader>epsilon ε
imap <Leader>e ε
imap <Leader>zeta ζ
imap <Leader>z ζ
imap <Leader>eta η
imap <Leader>h η
imap <Leader>theta θ
imap <Leader>iota ι
imap <Leader>i ι
imap <Leader>kappa κ
imap <Leader>k κ
imap <Leader>lambda λ
imap <Leader>l λ
imap <Leader>mu μ
imap <Leader>m μ
imap <Leader>nu ν
imap <Leader>n ν
imap <Leader>xi ξ
imap <Leader>omicron ο
imap <Leader>pi π
imap <Leader>p π
imap <Leader>rho ρ
imap <Leader>r ρ
imap <Leader>sigma σ
imap <Leader>s σ
imap <Leader>varsigma ς
imap <Leader>vars ς
imap <Leader>tau τ
imap <Leader>t τ
imap <Leader>u υ
imap <Leader>phi φ
imap <Leader>f φ
imap <Leader>chi χ
imap <Leader>x χ
imap <Leader>psi ψ
imap <Leader>c ψ
imap <Leader>omega ω
imap <Leader>v ω

imap <Leader>Alpha Α
imap <Leader>Beta Β
imap <Leader>Gamma Γ
imap <Leader>G Γ
imap <Leader>Delta Δ
imap <Leader>D Δ
imap <Leader>Epsilon Ε
imap <Leader>Zeta Ζ
imap <Leader>Eta Η
imap <Leader>Theta Θ
imap <Leader>Iota Ι
imap <Leader>Kappa Κ
imap <Leader>Lambda Λ
imap <Leader>L Λ
imap <Leader>Mu Μ
imap <Leader>Nu Ν
imap <Leader>Xi Ξ
imap <Leader>Omicron Ο
imap <Leader>Pi Π
imap <Leader>P Π
imap <Leader>Rho Ρ
imap <Leader>Sigma Σ
imap <Leader>S Σ
imap <Leader>Tau Τ
imap <Leader>Upsilon Υ
imap <Leader>Phi Φ
imap <Leader>F Φ
imap <Leader>Chi Χ
imap <Leader>Psi Ψ
imap <Leader>Omega Ω
imap <Leader>V Ω

cmap <Leader>over`  ̀
cmap <Leader>over'  ́
cmap <Leader>over^  ̂
cmap <Leader>overv  ̌
cmap <Leader>over~  ̃
cmap <Leader>over-  ̄
cmap <Leader>over_  ̅
cmap <Leader>over–  ̅
cmap <Leader>over—  ̅
cmap <Leader>overcup  ̆
cmap <Leader>overcap  ̑
cmap <Leader>over.  ̇
cmap <Leader>over..  ̈
cmap <Leader>over"  ̈
cmap <Leader>over...  ⃛
cmap <Leader>overright.  ͘
cmap <Leader>overo  ̊
cmap <Leader>over``  ̏
cmap <Leader>over''  ̋
cmap <Leader>overvec  ⃑
cmap <Leader>vec  ⃑
cmap <Leader>overlvec  ⃐
cmap <Leader>lvec  ⃐
cmap <Leader>overarc  ⃕
cmap <Leader>overlarc  ⃔
cmap <Leader>overto  ⃗
cmap <Leader>overfrom  ⃖
cmap <Leader>overfromto  ⃡
cmap <Leader>over*  ⃰
cmap <Leader>under`  ̖
cmap <Leader>under'  ̗
cmap <Leader>under,  ̗
cmap <Leader>under.  ̣
cmap <Leader>under..  ̤
cmap <Leader>under"  ̤
cmap <Leader>undero  ̥
cmap <Leader>under-  ̱
cmap <Leader>under_  ̲
cmap <Leader>under–  ̲
cmap <Leader>under—  ̲
cmap <Leader>through~  ̴
cmap <Leader>through-  ̵
cmap <Leader>through_  ̶
cmap <Leader>through–  ̶
cmap <Leader>through—  ̶
cmap <Leader>through/  ̷
cmap <Leader>not  ̷
cmap <Leader>through?  ̸
cmap <Leader>Not  ̸
cmap <Leader>through\|  ⃒
cmap <Leader>throughshortmid  ⃓
cmap <Leader>througho  ⃘

cmap <Leader>{{ ⦃
cmap <Leader>}} ⦄
cmap <Leader>: ∶
cmap <Leader>:: ∷
cmap <Leader>;  ﹔
cmap <Leader>.. ‥
cmap <Leader>=? ≟
cmap <Leader>all ∀
cmap <Leader>always □
cmap <Leader>approx ≈
cmap <Leader>bot ⊥
cmap <Leader>box □
cmap <Leader>boxdot ⊡
cmap <Leader>box. ⊡
cmap <Leader>boxminus ⊟
cmap <Leader>box- ⊟
cmap <Leader>boxplus ⊞
cmap <Leader>box+ ⊞
cmap <Leader>boxtimes ⊠
cmap <Leader>box* ⊠
cmap <Leader>bul •
cmap <Leader>C ℂ
cmap <Leader>cdot ∙
cmap <Leader>. ∙
cmap <Leader>cdots ⋯
cmap <Leader>check ✓
cmap <Leader>yes ✓
cmap <Leader>Check ✔
cmap <Leader>Yes ✔
cmap <Leader>circ ∘
cmap <Leader>clock ↻
cmap <Leader>cclock ↺
cmap <Leader>comp ∘
cmap <Leader>contra ↯
cmap <Leader>deg °
cmap <Leader>den ⟦⟧<left>
cmap <Leader>diamond ◇
cmap <Leader>dots …
cmap <Leader>down ↓
cmap <Leader>downtri ▼
cmap <Leader>Down ⇓
cmap <Leader>dunion ⊎
cmap <Leader>du ⊎
cmap <Leader>ell ℓ
cmap <Leader>empty ∅
cmap <Leader>equiv ≡
cmap <Leader>eq ≡
cmap <Leader>eventually ◇
cmap <Leader>exists ∃
cmap <Leader>flat ♭
cmap <Leader>fold ⦇⦈<left>
cmap <Leader>(\| ⦇
cmap <Leader>\|) ⦈
cmap <Leader>forall ∀
cmap <Leader>from ←
cmap <Leader><- ←
cmap <Leader>From ⇐
cmap <Leader>fromto ↔
cmap <Leader>Fromto ⇔
cmap <Leader>ge ≥
cmap <Leader>glub ⊓
cmap <Leader>iff ⇔
cmap <Leader>implies ⇒
cmap <Leader>impliedby ⇐
cmap <Leader>in ∈
cmap <Leader>infty ∞
cmap <Leader>inf ∞
cmap <Leader>int ∫
cmap <Leader>intersect ∩
cmap <Leader>iso ≅
cmap <Leader>join ⋈
cmap <Leader>land ∧
cmap <Leader>langle ⟨
cmap <Leader>lbrac ⟦
cmap <Leader>[[ ⟦
cmap <Leader>ldots …
cmap <Leader>ldown ⇃
cmap <Leader>leadsto ⇝
cmap <Leader>~> ⇝
cmap <Leader>le ≤
cmap <Leader>lift ⌊⌋<left>
cmap <Leader>floor ⌊⌋<left>
cmap <Leader>llangle ⟪
cmap <Leader>longto ⟶ 
cmap <Leader>-- ⟶ 
cmap <Leader>– ⟶ 
cmap <Leader>lor ∨
cmap <Leader>lower ⌈⌉<left>
cmap <Leader>ceil ⌈⌉<left>
cmap <Leader>lub ⊔
cmap <Leader>lup ↿
cmap <Leader>mapsto ↦
cmap <Leader>map ↦
cmap <Leader>mid ∣
cmap <Leader>models ⊨
cmap <Leader>\|= ⊨
cmap <Leader>N ℕ
cmap <Leader>ne ≠
cmap <Leader>nearrow ↗
cmap <Leader>Nearrow ⇗
cmap <Leader>neg ¬
cmap <Leader>/= ≠
cmap <Leader>nequiv ≢
cmap <Leader>neq ≢
cmap <Leader>nexist ∄
cmap <Leader>none ∄
cmap <Leader>ni ∋
cmap <Leader>ni ∋
cmap <Leader>nin ∉
cmap <Leader>niso ≇
cmap <Leader>notin ∉
cmap <Leader>nwarrow ↖
cmap <Leader>Nwarrow ⇖
cmap <Leader>oast ⊛
cmap <Leader>odot ⊙
cmap <Leader>o. ⊙
cmap <Leader>of ∘
cmap <Leader>o ∘
cmap <Leader>ominus ⊖
cmap <Leader>o- ⊖
cmap <Leader>oplus ⊕
cmap <Leader>o+ ⊕
cmap <Leader>oslash ⊘
cmap <Leader>o/ ⊘
cmap <Leader>otimes ⊗
cmap <Leader>o* ⊗
cmap <Leader>par ∂
cmap <Leader>pge ≽
cmap <Leader>pgt ≻
cmap <Leader>ple ≼
cmap <Leader>plt ≺
cmap <Leader>p≥ ≽
cmap <Leader>p> ≻
cmap <Leader>p≤ ≼
cmap <Leader>p< ≺
cmap <Leader>pm ±
cmap <Leader>prec ≼
cmap <Leader>prod ∏
cmap <Leader>proves ⊢
cmap <Leader>\|- ⊢
cmap <Leader>provedby ⊣
cmap <Leader>Q ℚ
cmap <Leader>qed ∎
cmap <Leader>R ℝ
cmap <Leader>rangle ⟩
cmap <Leader>rbrac ⟧
cmap <Leader>]] ⟧
cmap <Leader>rdown ⇂
cmap <Leader>righttri ▸
cmap <Leader>rrangle ⟫
cmap <Leader>rup ↾
cmap <Leader>searrow ↘
cmap <Leader>Searrow ⇘
cmap <Leader>setminus ∖
cmap <Leader>sharp ♯
cmap <Leader># ♯
cmap <Leader>sim ∼
cmap <Leader>simeq ≃
cmap <Leader>some ∃
cmap <Leader>sqge ⊒
cmap <Leader>sqgt ⊐
cmap <Leader>sqle ⊑
cmap <Leader>sqlt ⊏
cmap <Leader>s≥ ⊒
cmap <Leader>s> ⊐
cmap <Leader>s≤ ⊑
cmap <Leader>s< ⊏
cmap <Leader>sqr ²
cmap <Leader>sqrt √
cmap <Leader>star ✭
cmap <Leader>subset ⊂
cmap <Leader>sub ⊂
cmap <Leader>subseteq ⊆
cmap <Leader>subeq ⊆
cmap <Leader>subsetneq ⊊
cmap <Leader>subneq ⊊
cmap <Leader>sum ∑
cmap <Leader>supset ⊃
cmap <Leader>sup ⊃
cmap <Leader>supseteq ⊇
cmap <Leader>supeq ⊇
cmap <Leader>supsetneq ⊋
cmap <Leader>supneq ⊋
cmap <Leader>swarrow ↙
cmap <Leader>Swarrow ⇙
cmap <Leader>thus ∴
cmap <Leader>times ×
cmap <Leader>* ×
cmap <Leader>to →
cmap <Leader>- →
cmap <C-_> →
cmap <Leader>To ⇒
cmap <Leader>= ⇒
cmap <Leader>top ⊤
cmap <Leader>tuple ⟨⟩<left>
cmap <Leader>up ↑
cmap <Leader>updown ↕
cmap <Leader>ud ↕
cmap <Leader>unfold ⦉⦊<left>
cmap <Leader><\| ⦉
cmap <Leader>\|> ⦊
cmap <Leader>up;down ⇅
cmap <Leader>u;d ⇅
cmap <Leader>uptri ▲
cmap <Leader>Up ⇑
cmap <Leader>union ∪
cmap <Leader>vdots ⋮
cmap <Leader>voltage ⚡
cmap <Leader>xmark ✗
cmap <Leader>no ✗
cmap <Leader>Xmark ✘
cmap <Leader>No ✘
cmap <Leader>Z ℤ

cmap <Leader>sec §

cmap <Leader>^0 ⁰
cmap <Leader>^1 ¹
cmap <Leader>^2 ²
cmap <Leader>^3 ³
cmap <Leader>^4 ⁴
cmap <Leader>^5 ⁵
cmap <Leader>^6 ⁶
cmap <Leader>^7 ⁷
cmap <Leader>^8 ⁸
cmap <Leader>^9 ⁹
cmap <Leader>^n ⁿ
cmap <Leader>^i ⁱ
cmap <Leader>^+ ⁺
cmap <Leader>^- ⁻
cmap <Leader>' ′
cmap <Leader>'' ″
cmap <Leader>''' ‴
cmap <Leader>'''' ⁗
cmap <Leader>" ″
cmap <Leader>"" ⁗
cmap <Leader>` ‵
cmap <Leader>`` ‶
cmap <Leader>``` ‷

cmap <Leader>0 ₀
cmap <Leader>1 ₁
cmap <Leader>2 ₂
cmap <Leader>3 ₃
cmap <Leader>4 ₄
cmap <Leader>5 ₅
cmap <Leader>6 ₆
cmap <Leader>7 ₇
cmap <Leader>8 ₈
cmap <Leader>9 ₉
cmap <Leader>_i ᵢ
cmap <Leader>_j ⱼ
cmap <Leader>_+ ₊
cmap <Leader>_- ₋
cmap <Leader>p0 π₀
cmap <Leader>p1 π₁
cmap <Leader>p2 π₂
cmap <Leader>p3 π₃
cmap <Leader>p4 π₄
cmap <Leader>p5 π₅
cmap <Leader>p6 π₆
cmap <Leader>p7 π₇
cmap <Leader>p8 π₈
cmap <Leader>p9 π₉
cmap <Leader>i0 ι₀
cmap <Leader>i1 ι₁
cmap <Leader>i2 ι₂
cmap <Leader>i3 ι₃
cmap <Leader>i4 ι₄
cmap <Leader>i5 ι₅
cmap <Leader>i6 ι₆
cmap <Leader>i7 ι₇
cmap <Leader>i8 ι₈
cmap <Leader>i9 ι₉

cmap <Leader>alpha α
cmap <Leader>a α
cmap <Leader>beta β
cmap <Leader>b β
cmap <Leader>gamma γ
cmap <Leader>g γ
cmap <Leader>delta δ
cmap <Leader>d δ
cmap <Leader>epsilon ε
cmap <Leader>e ε
cmap <Leader>zeta ζ
cmap <Leader>z ζ
cmap <Leader>eta η
cmap <Leader>h η
cmap <Leader>theta θ
cmap <Leader>iota ι
cmap <Leader>i ι
cmap <Leader>kappa κ
cmap <Leader>k κ
cmap <Leader>lambda λ
cmap <Leader>l λ
cmap <Leader>mu μ
cmap <Leader>m μ
cmap <Leader>nu ν
cmap <Leader>n ν
cmap <Leader>xi ξ
cmap <Leader>omicron ο
cmap <Leader>pi π
cmap <Leader>p π
cmap <Leader>rho ρ
cmap <Leader>r ρ
cmap <Leader>sigma σ
cmap <Leader>s σ
cmap <Leader>varsigma ς
cmap <Leader>vars ς
cmap <Leader>tau τ
cmap <Leader>t τ
cmap <Leader>u υ
cmap <Leader>phi φ
cmap <Leader>f φ
cmap <Leader>chi χ
cmap <Leader>x χ
cmap <Leader>psi ψ
cmap <Leader>c ψ
cmap <Leader>omega ω
cmap <Leader>v ω

cmap <Leader>Alpha Α
cmap <Leader>Beta Β
cmap <Leader>Gamma Γ
cmap <Leader>G Γ
cmap <Leader>Delta Δ
cmap <Leader>D Δ
cmap <Leader>Epsilon Ε
cmap <Leader>Zeta Ζ
cmap <Leader>Eta Η
cmap <Leader>Theta Θ
cmap <Leader>Iota Ι
cmap <Leader>Kappa Κ
cmap <Leader>Lambda Λ
cmap <Leader>L Λ
cmap <Leader>Mu Μ
cmap <Leader>Nu Ν
cmap <Leader>Xi Ξ
cmap <Leader>Omicron Ο
cmap <Leader>Pi Π
cmap <Leader>P Π
cmap <Leader>Rho Ρ
cmap <Leader>Sigma Σ
cmap <Leader>S Σ
cmap <Leader>Tau Τ
cmap <Leader>Upsilon Υ
cmap <Leader>Phi Φ
cmap <Leader>F Φ
cmap <Leader>Chi Χ
cmap <Leader>Psi Ψ
cmap <Leader>Omega Ω
cmap <Leader>V Ω

